//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MianPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredServices
    {
        public string UserName { get; set; }
        public int IDService { get; set; }
        public short IDStatus { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual ProvidedServices ProvidedServices { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
    }
}
